### ISSUE TITLE
lean up failed when port 3000 was occupied

### ISSUE THREAD

**Issue by jonashao** [leancloud/static-getting-started#3]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (C:\Web\Projects\LeanCloud\example\static-getting-started\server.js:10:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by aisk** [comment]
请尝试关掉占用 3000 端口的进程，或者参考文档 https://leancloud.cn/docs/leanengine_cli.html#%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C ，使用 `lean up --port=xxxx` 来指定其他端口。
